### ISSUE TITLE
v2 umbrella issue

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie-custom/blender.js#16]
## Goals

- Modules shouldn't do anything, just export functionality
- Some sort of bootstrap file would be ok, e.g. for registering the csrf header
- Ideally modules can be used outside of this package's context, but that's not a requirement
- Embrace ES6, modify code to follow our style guide
- No more globals

## Also...

- [ ] Rename to `@spatie/blender-js`
- [ ] Update `@spatie/blender-css` accordingly
- [ ] Expose everything through `index`, so we don't need to import paths in our projects

## Overview

| Module                        | Todo                                  | Issue |
| ----------------------------- | ------------------------------------- | ----- |
| ajax.csrf.js                  | Replace jQuery with axios for ajax    | #7    |
| form.autosave.js              | Deprecated, remove                    | #8    |
| form.input.datetimepicker.js  | Replace with Pikaday                  | #9    |
| form.locationpicker.js        | Needs rewrite or alternative          | #10   |
| form.select.js                | ?? Find a new lib                     | #11   |
| form.textarea.autosize.js     | Minor refactors to remove jQuery      | #12   |
| form.textarea.editor.js       | Minor refactors to remove jQuery      | #12   |
| form.textarea.parts.js        | Deprecated, remove                    | #8    |
| interface.confirm.js          | ?? Find a new lib                     | #13   |
| interface.translations.js     | Deprecated, remove                    | #8    |
| table.datatables.js           | ?? Find a new lib                     | #14   |
| table.sortable.js             | See `datatables`                      | #14   |
| tabs.js                       | Needs rewrite without jQuery          | #15   |

**Comment by sebastiandedeyne** [comment]
I'd suggest creating a branch in `blender` to develop this, and when we're done, extract it to this package.
